# Generated by Django 3.0.2 on 2020-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docter_name', models.CharField(max_length=100)),
                ('docter_type', models.CharField(max_length=100)),
                ('docter_quali', models.CharField(max_length=100)),
                ('doctor_exp', models.DateField(default='2019-10-05')),
                ('docter_image', models.ImageField(default='None', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_disease', models.CharField(max_length=100)),
                ('patient_photo', models.ImageField(default='None', upload_to='images/')),
                ('patient', models.CharField(max_length=100)),
            ],
        ),
    ]
