# Generated by Django 3.0.2 on 2020-12-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docter',
            name='docter_image',
        ),
        migrations.RemoveField(
            model_name='docter',
            name='docter_quali',
        ),
    ]
