# Generated by Django 3.0.2 on 2020-12-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthline', '0002_auto_20201212_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docter',
            name='doctor_exp',
            field=models.IntegerField(default=0),
        ),
    ]
